% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Homework 03},
  pdfauthor={Alabboodi, Ammar (email: ANA154@pitt.edu)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Homework 03}
\author{Alabboodi, Ammar (email:
\href{mailto:ANA154@pitt.edu}{\nolinkurl{ANA154@pitt.edu}})}
\date{today}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{Overview}\label{overview}

\subparagraph{\texorpdfstring{This analysis explores TikTok posts that
use the hashtag \textbf{\#edrecovery}, which stands for \emph{eating
disorder recovery}. The goal is to understand common themes and
communities emerging around this tag by examining co-occurring hashtags,
performing text-based clustering, and visualizing groupings using
dimensionality
reduction.}{This analysis explores TikTok posts that use the hashtag \#edrecovery, which stands for eating disorder recovery. The goal is to understand common themes and communities emerging around this tag by examining co-occurring hashtags, performing text-based clustering, and visualizing groupings using dimensionality reduction.}}\label{this-analysis-explores-tiktok-posts-that-use-the-hashtag-edrecovery-which-stands-for-eating-disorder-recovery.-the-goal-is-to-understand-common-themes-and-communities-emerging-around-this-tag-by-examining-co-occurring-hashtags-performing-text-based-clustering-and-visualizing-groupings-using-dimensionality-reduction.}

\subparagraph{\texorpdfstring{We obtained the data from a CSV file named
\texttt{tiktok\_hashtags.csv}, which contains usernames and associated
hashtags used in TikTok posts. Each row represents a post and its
corresponding hashtag
string.}{We obtained the data from a CSV file named tiktok\_hashtags.csv, which contains usernames and associated hashtags used in TikTok posts. Each row represents a post and its corresponding hashtag string.}}\label{we-obtained-the-data-from-a-csv-file-named-tiktok_hashtags.csv-which-contains-usernames-and-associated-hashtags-used-in-tiktok-posts.-each-row-represents-a-post-and-its-corresponding-hashtag-string.}

The main steps in this analysis include:

\begin{itemize}
\item
  \textbf{Parsing and normalizing hashtags}, extracting all hashtags
  from each post and standardizing them (lowercasing and cleaning).
\item
  \textbf{Identifying top co-occurring hashtags} with
  \texttt{\#edrecovery} to highlight commonly discussed topics.
\item
  \textbf{Constructing a Document-Term Matrix (DTM)} and applying
  \textbf{TF--IDF (Term Frequency - Inverse Document Frequency)
  weighting} to emphasize significant hashtags per post.
\item
  \textbf{Clustering posts} using \textbf{K-means} based on their
  hashtag profiles to uncover distinct communities or thematic groups.
\item
  \textbf{Visualizing clusters} using \textbf{Principal Component
  Analysis (PCA)} to reduce dimensionality and reveal separable
  clusters.
\item
  \textbf{Profiling each cluster} by identifying the most representative
  hashtags for interpretation.
\end{itemize}

\subparagraph{This process helps us explore how TikTok users engage with
the concept of recovery, the narratives they construct, and the
subcultures that form within the broader \#edrecovery
discourse.}\label{this-process-helps-us-explore-how-tiktok-users-engage-with-the-concept-of-recovery-the-narratives-they-construct-and-the-subcultures-that-form-within-the-broader-edrecovery-discourse.}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# install.packages(c("tidyverse","tidytext","tm","ggplot2","factoextra"))}
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v dplyr     1.1.4     v readr     2.1.5
## v forcats   1.0.0     v stringr   1.5.1
## v ggplot2   3.5.2     v tibble    3.2.1
## v lubridate 1.9.4     v tidyr     1.3.1
## v purrr     1.0.2     
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidytext)}
\FunctionTok{library}\NormalTok{(tm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: NLP
## 
## Attaching package: 'NLP'
## 
## The following object is masked from 'package:ggplot2':
## 
##     annotate
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(factoextra)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load \& parse}
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"tiktok\_hashtags.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 3375 Columns: 4
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## chr (2): username, hashtags
## dbl (1): video_id
## lgl (1): video_url
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \CommentTok{\# extract all "\#word" tokens}
    \AttributeTok{tags =} \FunctionTok{str\_extract\_all}\NormalTok{(hashtags, }\StringTok{"\#}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{w+"}\NormalTok{),}
    \CommentTok{\# normalize: lowercase + replace zero→o + unique}
    \AttributeTok{tags =} \FunctionTok{map}\NormalTok{(tags, }\SpecialCharTok{\textasciitilde{}} \FunctionTok{unique}\NormalTok{(}\FunctionTok{tolower}\NormalTok{(}\FunctionTok{gsub}\NormalTok{(}\StringTok{"0"}\NormalTok{, }\StringTok{"o"}\NormalTok{, .x)))),}
    \CommentTok{\# add a doc\_id for later joins}
    \AttributeTok{doc\_id =} \FunctionTok{row\_number}\NormalTok{()}
\NormalTok{  )}

\CommentTok{\# Co‑occurrence with \#edrecovery}
\NormalTok{ed\_df }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(}\FunctionTok{map\_lgl}\NormalTok{(tags, }\SpecialCharTok{\textasciitilde{}} \StringTok{"\#edrecovery"} \SpecialCharTok{\%in\%}\NormalTok{ .x))}

\NormalTok{co\_occur }\OtherTok{\textless{}{-}}\NormalTok{ ed\_df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{unnest}\NormalTok{(tags) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(tags }\SpecialCharTok{!=} \StringTok{"\#edrecovery"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(tags, }\AttributeTok{sort =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice\_head}\NormalTok{(}\AttributeTok{n =} \DecValTok{20}\NormalTok{)}

\FunctionTok{ggplot}\NormalTok{(co\_occur, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(tags, n), }\AttributeTok{y =}\NormalTok{ n, }\AttributeTok{fill =}\NormalTok{ n)) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{coord\_flip}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_gradient}\NormalTok{(}\AttributeTok{low =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{high =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Top 20 Hashtags Co‑occurring with \#edrecovery"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Hashtag"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Count"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{model_files/figure-latex/unnamed-chunk-1-1.pdf}

\subsection{Co‑occurrence Analysis}\label{cooccurrence-analysis}

To better understand the thematic context of posts using
\textbf{\#edrecovery}, we first identified all hashtags that co-occur
with it. After loading and parsing the dataset, we extracted hashtags
from each post, normalized them by lowercasing and replacing zeros with
the letter ``o'', and assigned a unique document ID to each entry.

We then filtered the dataset to include only those posts containing
\texttt{\#edrecovery} and computed the frequency of all other hashtags
that appear alongside it. The top 20 co-occurring hashtags were
visualized using a horizontal bar chart with a gradient fill,
emphasizing which tags most frequently accompany \texttt{\#edrecovery}.

This analysis gives us an initial glimpse into the most common themes
and conversations that surround the recovery community on TikTok.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Build a DTM with TF{-}IDF for all videos}
\NormalTok{docs }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{transmute}\NormalTok{(}
\NormalTok{    doc\_id,}
    \AttributeTok{text =} \FunctionTok{map\_chr}\NormalTok{(tags, paste, }\AttributeTok{collapse =} \StringTok{" "}\NormalTok{)}
\NormalTok{  )}

\CommentTok{\# Remove any rows with N/A or missing terms}
\NormalTok{docs }\OtherTok{\textless{}{-}}\NormalTok{ docs }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(text) }\SpecialCharTok{\&}\NormalTok{ text }\SpecialCharTok{!=} \StringTok{""}\NormalTok{)}

\CommentTok{\# Create the DTM}
\NormalTok{dtm }\OtherTok{\textless{}{-}}\NormalTok{ docs }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{unnest\_tokens}\NormalTok{(term, text) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(doc\_id, term, }\AttributeTok{sort =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{cast\_dtm}\NormalTok{(doc\_id, term, n)}

\CommentTok{\# Apply TF{-}IDF weighting}
\NormalTok{dtm\_tfidf }\OtherTok{\textless{}{-}} \FunctionTok{weightTfIdf}\NormalTok{(dtm)}
\NormalTok{m }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(dtm\_tfidf)}

\CommentTok{\# Remove empty documents (rows with no terms)}
\NormalTok{non\_empty }\OtherTok{\textless{}{-}} \FunctionTok{rowSums}\NormalTok{(m) }\SpecialCharTok{\textgreater{}} \DecValTok{0}
\NormalTok{m\_nz }\OtherTok{\textless{}{-}}\NormalTok{ m[non\_empty, ]}

\CommentTok{\# L2{-}normalize each row (document)}
\NormalTok{row\_norms }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{rowSums}\NormalTok{(m\_nz}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\NormalTok{m\_nz }\OtherTok{\textless{}{-}}\NormalTok{ m\_nz }\SpecialCharTok{/}\NormalTok{ row\_norms}

\CommentTok{\# Choose k (number of clusters) ≤ nrow(m\_nz)−1}
\NormalTok{k }\OtherTok{\textless{}{-}} \FunctionTok{min}\NormalTok{(}\DecValTok{5}\NormalTok{, }\FunctionTok{nrow}\NormalTok{(m\_nz) }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{42}\NormalTok{)}
\NormalTok{km }\OtherTok{\textless{}{-}} \FunctionTok{kmeans}\NormalTok{(m\_nz, }\AttributeTok{centers =}\NormalTok{ k, }\AttributeTok{nstart =} \DecValTok{25}\NormalTok{)}

\CommentTok{\# Perform PCA on the normalized matrix}
\NormalTok{pca\_res }\OtherTok{\textless{}{-}} \FunctionTok{prcomp}\NormalTok{(m\_nz, }\AttributeTok{center =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{scale. =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{scores }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{PC1 =}\NormalTok{ pca\_res}\SpecialCharTok{$}\NormalTok{x[,}\DecValTok{1}\NormalTok{],}
  \AttributeTok{PC2 =}\NormalTok{ pca\_res}\SpecialCharTok{$}\NormalTok{x[,}\DecValTok{2}\NormalTok{],}
  \AttributeTok{cluster =} \FunctionTok{factor}\NormalTok{(km}\SpecialCharTok{$}\NormalTok{cluster)}
\NormalTok{)}

\CommentTok{\# Plot the results}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{ggplot}\NormalTok{(scores, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ PC1, }\AttributeTok{y =}\NormalTok{ PC2, }\AttributeTok{color =}\NormalTok{ cluster)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{, }\AttributeTok{size =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \FunctionTok{paste0}\NormalTok{(}\StringTok{"PCA of Videos Colored by K{-}means Cluster (k="}\NormalTok{, k, }\StringTok{")"}\NormalTok{),}
    \AttributeTok{x =} \StringTok{"PC1"}\NormalTok{, }\AttributeTok{y =} \StringTok{"PC2"}\NormalTok{, }\AttributeTok{color =} \StringTok{"Cluster"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{model_files/figure-latex/unnamed-chunk-2-1.pdf}

\subsection{Clustering and Dimensionality
Reduction}\label{clustering-and-dimensionality-reduction}

To identify latent themes among all TikTok posts---not just those
containing \texttt{\#edrecovery}---we constructed a
\textbf{Document-Term Matrix (DTM)} using the full set of normalized
hashtags. We applied \textbf{TF--IDF weighting} to emphasize hashtags
that are more informative within individual posts while down-weighting
those that are too common across the dataset.

After removing empty documents, we performed \textbf{L2 normalization}
on the TF--IDF matrix to prepare it for clustering. We used
\textbf{K-means clustering} (with \texttt{k} set dynamically to a
maximum of 5, or fewer if the dataset was smaller) to group posts based
on hashtag similarity.

To visualize these clusters in two dimensions, we applied
\textbf{Principal Component Analysis (PCA)} on the normalized matrix and
plotted the first two principal components. The resulting scatter plot
reveals distinct clusters, each representing a different thematic
grouping of TikTok posts based on hashtag usage patterns.

\subsubsection{Graph Reading}\label{graph-reading}

That scatter is a map of videos in a two‑dimensional ``hashtag space,''
where:

\textbf{PC1 (x‑axis)} captures the single biggest direction of variation
in how videos use hashtags.

\textbf{PC2 (y‑axis)} captures the next‑biggest, orthogonal direction of
variation.

\textbf{Clusters (colors):} Videos in the same color are those that the
k‑means algorithm judged to have similar TF--IDF hashtag signatures.

\textbf{Distance from each other:} Two videos plotted close together
used almost the same mix of hashtags.

\textbf{Distance from the origin:} Videos far out on PC1 or PC2 have
``extreme'' hashtag mixes in that direction. Videos near (0,0) use a
more ``average'' combination. \textbf{Cluster separation:}
Well‑separated blobs mean distinct hashtag communities. Overlap suggests
videos that mix hashtags from multiple themes.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{loadings }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(pca\_res}\SpecialCharTok{$}\NormalTok{rotation[,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{])}
\CommentTok{\# show top positive/negative hashtags on PC1}
\FunctionTok{head}\NormalTok{(}\FunctionTok{arrange}\NormalTok{(loadings, }\FunctionTok{desc}\NormalTok{(PC1)), }\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                           PC1          PC2
## edrecovery          0.3259355 -0.193220413
## recoveryispossible  0.2838019  0.326971167
## fyp                 0.2765249 -0.176166859
## recoverytok         0.2560255  0.420154709
## 3drecovery          0.2475108  0.203485741
## mentalhealthmatters 0.2222289 -0.005893994
## mentalhealth        0.2220142 -0.104768987
## anarecovry          0.2107249 -0.115194729
## anarecovery         0.2047522 -0.039310268
## シ                  0.1943413 -0.150222006
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(}\FunctionTok{arrange}\NormalTok{(loadings, PC1), }\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                 PC1 PC2
## hispanic          0   0
## latina            0   0
## nosabokid         0   0
## ilovebooks        0   0
## literaryfiction   0   0
## oceanvuong        0   0
## reader            0   0
## richardsiken      0   0
## sallyrooney       0   0
## veschwab          0   0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(tidyr)}
\CommentTok{\# 1. Ensure no NAs in the \textquotesingle{}tags\textquotesingle{} column of df}
\NormalTok{df\_clean }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(tags) }\SpecialCharTok{\&}\NormalTok{ tags }\SpecialCharTok{!=} \StringTok{""}\NormalTok{)  }\CommentTok{\# Remove rows with NAs or empty tags}

\CommentTok{\# Build a DTM with TF{-}IDF for all videos}
\NormalTok{docs }\OtherTok{\textless{}{-}}\NormalTok{ df\_clean }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{transmute}\NormalTok{(}
\NormalTok{    doc\_id,}
    \AttributeTok{text =} \FunctionTok{map\_chr}\NormalTok{(tags, paste, }\AttributeTok{collapse =} \StringTok{" "}\NormalTok{)}
\NormalTok{  )}

\CommentTok{\# Create the DTM}
\NormalTok{dtm }\OtherTok{\textless{}{-}}\NormalTok{ docs }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{unnest\_tokens}\NormalTok{(term, text) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(doc\_id, term, }\AttributeTok{sort =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{cast\_dtm}\NormalTok{(doc\_id, term, n)}

\CommentTok{\# Apply TF{-}IDF}
\NormalTok{dtm\_tfidf }\OtherTok{\textless{}{-}} \FunctionTok{weightTfIdf}\NormalTok{(dtm)}
\NormalTok{m }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(dtm\_tfidf)}

\CommentTok{\# 2. Remove any all{-}zero rows (this ensures no empty documents)}
\NormalTok{non\_zero\_mask }\OtherTok{\textless{}{-}} \FunctionTok{rowSums}\NormalTok{(m) }\SpecialCharTok{\textgreater{}} \DecValTok{0}
\NormalTok{m\_nz }\OtherTok{\textless{}{-}}\NormalTok{ m[non\_zero\_mask, , drop }\OtherTok{=} \ConstantTok{FALSE}\NormalTok{]}
\NormalTok{valid\_doc\_ids }\OtherTok{\textless{}{-}} \FunctionTok{as.integer}\NormalTok{(}\FunctionTok{rownames}\NormalTok{(m\_nz))}

\CommentTok{\# 3. Run k{-}means on the filtered matrix}
\NormalTok{k }\OtherTok{\textless{}{-}} \FunctionTok{min}\NormalTok{(}\DecValTok{5}\NormalTok{, }\FunctionTok{nrow}\NormalTok{(m\_nz) }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{42}\NormalTok{)}
\NormalTok{km }\OtherTok{\textless{}{-}} \FunctionTok{kmeans}\NormalTok{(m\_nz, }\AttributeTok{centers =}\NormalTok{ k, }\AttributeTok{nstart =} \DecValTok{25}\NormalTok{)}

\CommentTok{\# 4. Build a map of doc\_id → cluster}
\NormalTok{cluster\_map }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{doc\_id =}\NormalTok{ valid\_doc\_ids,}
  \AttributeTok{cluster =} \FunctionTok{factor}\NormalTok{(km}\SpecialCharTok{$}\NormalTok{cluster)}
\NormalTok{)}

\CommentTok{\# 5. Subset the original df by valid doc\_ids (those that are not empty or NA)}
\NormalTok{df\_nz }\OtherTok{\textless{}{-}}\NormalTok{ df\_clean }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(doc\_id }\SpecialCharTok{\%in\%}\NormalTok{ valid\_doc\_ids) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{left\_join}\NormalTok{(cluster\_map, }\AttributeTok{by =} \StringTok{"doc\_id"}\NormalTok{)}

\CommentTok{\# 6. Now unnest and tally top tags per cluster}
\NormalTok{top\_tags\_per\_cluster }\OtherTok{\textless{}{-}}\NormalTok{ df\_nz }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{unnest}\NormalTok{(tags) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(cluster, tags) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{count =} \FunctionTok{n}\NormalTok{(), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(cluster, }\FunctionTok{desc}\NormalTok{(count)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(cluster) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice\_head}\NormalTok{(}\AttributeTok{n =} \DecValTok{5}\NormalTok{)}

\FunctionTok{print}\NormalTok{(top\_tags\_per\_cluster)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 18 x 3
## # Groups:   cluster [5]
##    cluster tags                       count
##    <fct>   <chr>                      <int>
##  1 1       #greenscreenvideo              4
##  2 1       #onthisday                     3
##  3 1       #collegelife                   2
##  4 2       #recovery                     94
##  5 2       #edrecovery                   91
##  6 2       #edrecovry                    79
##  7 2       #anarecoveryy                 70
##  8 2       #anarecovery                  59
##  9 3       #real                         28
## 10 3       #exerciseaddictionrecovery     8
## 11 4       #ootd                         10
## 12 4       #fitcheck                      2
## 13 4       #gifted                        1
## 14 5       #fyp                         831
## 15 5       #edrecovery                  542
## 16 5       #mentalhealth                444
## 17 5       #recoveryispossible          438
## 18 5       #mentalhealthmatters         395
\end{verbatim}

\section{Cluster Interpretation of \#edrecovery TikTok Hashtag
Data}\label{cluster-interpretation-of-edrecovery-tiktok-hashtag-data}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Cluster 1: \#personal\_reflection --- Nostalgia and Identity
Exploration}\label{cluster-1-personal_reflection-nostalgia-and-identity-exploration}

\textbf{Top hashtags:} \#greenscreenvideo (4), \#onthisday (3),
\#collegelife (2)

\textbf{Description:}\\

This cluster reflects content centered around personal reflection,
nostalgic moments, and identity exploration. Hashtags like
\#greenscreenvideo indicate the use of multimedia tools, possibly adding
a creative layer to personal storytelling. The presence of \#onthisday
points to a focus on remembering significant past events, and
\#collegelife suggests a connection to youthful or academic experiences,
indicating that users in this cluster may be revisiting or reflecting on
their journey, particularly during the college years.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{Cluster 2: \#mental\_health\_struggles --- Mental Health
\& Recovery
Challenges}\label{cluster-2-mental_health_struggles-mental-health-recovery-challenges}

\textbf{Top hashtags:} \#recovery (94), \#edrecovery (91), \#edrecovry
(79), \#anarecoveryy (70), \#anarecovery (59)

\textbf{Description:}\\

This cluster captures themes of mental health recovery, with a
particular focus on eating disorders. The hashtags \#edrecovery,
\#edrecovry, \#anarecoveryy, and \#anarecovery emphasize struggles and
recovery from eating disorders, while \#recovery and \#edrecovery are
commonly used in broader mental health discussions. The recurrence of
similar recovery-focused hashtags suggests that this cluster is
dedicated to sharing personal recovery narratives, supporting those on
similar journeys, and fostering a sense of community and solidarity.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{Cluster 3: \#authenticity\_and\_vulnerability --- Raw and
Unfiltered Recovery
Stories}\label{cluster-3-authenticity_and_vulnerability-raw-and-unfiltered-recovery-stories}

\textbf{Top hashtags:} \#real (28), \#exerciseaddictionrecovery (8)

\textbf{Description:}\\

This cluster emphasizes authenticity and vulnerability in the context of
mental health and recovery. The dominant hashtag, \#real, reflects
content that likely focuses on raw, unfiltered personal experiences.
It's a space for those who reject the polished or curated side of social
media, sharing what recovery really looks like. The addition of
\#exerciseaddictionrecovery points to a specific form of recovery,
indicating that users in this cluster may also be grappling with
addiction and the journey to overcome it.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{Cluster 4: \#style\_and\_self\_image --- Appearance and
Personal
Expression}\label{cluster-4-style_and_self_image-appearance-and-personal-expression}

\textbf{Top hashtags:} \#ootd (10), \#fitcheck (2), \#gifted (1)

\textbf{Description:}\\

This cluster blends elements of personal expression and self-image with
the theme of recovery. The hashtag \#ootd (outfit of the day) is a
common marker for showcasing personal style, while \#fitcheck suggests a
focus on physical appearance, likely tying into body image and
self-confidence issues. The inclusion of \#gifted may indicate a
connection to personal growth or empowerment, possibly in the context of
recognizing strengths during recovery or self-reflection.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{Cluster 5: \#mainstream\_recovery\_and\_awareness ---
Broad Mental Health
Advocacy}\label{cluster-5-mainstream_recovery_and_awareness-broad-mental-health-advocacy}

\textbf{Top hashtags:} \#fyp (831), \#edrecovery (542), \#mentalhealth
(444), \#recoveryispossible (438), \#mentalhealthmatters (395)

\textbf{Description:}\\

The largest cluster, this one represents a broad and mainstream approach
to recovery and mental health advocacy. The prominence of the \#fyp
hashtag indicates that this content is aimed at reaching a wide audience
on TikTok, likely showing up on users' For You Pages. Hashtags like
\#mentalhealth, \#recoveryispossible, and \#mentalhealthmatters suggest
a focus on awareness, hope, and support, making this cluster central to
the broader conversation around mental health recovery and solidarity.
This cluster is likely filled with educational content, inspirational
messages, and general recovery-related discussions aimed at a wide and
diverse audience.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Compute Purity and Entropy per cluster}
\FunctionTok{library}\NormalTok{(dplyr)}

\CommentTok{\# Helper function for entropy}
\NormalTok{entropy }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(p) \{}
\NormalTok{  p }\OtherTok{\textless{}{-}}\NormalTok{ p[p }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{]}
  \SpecialCharTok{{-}}\FunctionTok{sum}\NormalTok{(p }\SpecialCharTok{*} \FunctionTok{log2}\NormalTok{(p))}
\NormalTok{\}}

\CommentTok{\# Purity and entropy calculation}
\NormalTok{cluster\_eval }\OtherTok{\textless{}{-}}\NormalTok{ df\_nz }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{unnest}\NormalTok{(tags) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(cluster, tags) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{count =} \FunctionTok{n}\NormalTok{(), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(cluster) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{total =} \FunctionTok{sum}\NormalTok{(count),}
         \AttributeTok{prop =}\NormalTok{ count }\SpecialCharTok{/}\NormalTok{ total) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{top\_tag =} \FunctionTok{first}\NormalTok{(tags),}
    \AttributeTok{top\_tag\_prop =} \FunctionTok{max}\NormalTok{(prop),}
    \AttributeTok{cluster\_entropy =} \FunctionTok{entropy}\NormalTok{(prop)}
\NormalTok{  )}

\NormalTok{cluster\_eval}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 5 x 4
##   cluster top_tag                    top_tag_prop cluster_entropy
##   <fct>   <chr>                             <dbl>           <dbl>
## 1 1       #collegelife                     0.444            1.53 
## 2 2       #1                               0.0906           5.56 
## 3 3       #exerciseaddictionrecovery       0.778            0.764
## 4 4       #fitcheck                        0.769            0.991
## 5 5       #1                               0.0509           8.73
\end{verbatim}

\subsubsection{Cluster 1:}\label{cluster-1}

Cluster 1, centered around \#collegelife, shows a moderate purity of
44.44\% and an entropy of 1.53. This suggests that the majority of posts
in this cluster are centered on the theme of college life, but there is
still some diversity in the content, reflecting a range of personal
experiences related to mental health and recovery during the college
years. It is not a perfectly homogeneous group but has a clear focus on
the college experience.

\subsubsection{Cluster 2:}\label{cluster-2}

Cluster 2, with the top hashtags \#1, shows low purity (9.09\%) and very
high entropy (5.56 / 8.73). This indicates that the cluster is highly
mixed, with no strong single theme dominating. Posts here likely feature
a range of content, from personal achievements to varied recovery
narratives, making this cluster noisy and difficult to classify into one
clear theme. The repetition of the hashtag \#1 suggests a possible focus
on individual milestones or recognition, but the diversity of topics
makes it more scattered.

\subsubsection{Cluster 3:}\label{cluster-3}

Cluster 3, centered around \#exerciseaddictionrecovery, has a high
purity of 77.78\% and low entropy of 0.76. This indicates a very
coherent and focused group of posts primarily centered around recovery
from exercise addiction. Most posts in this cluster prominently feature
\#exerciseaddictionrecovery, and the content remains tightly related to
this theme, making it one of the more focused and consistent clusters.

\subsubsection{Cluster 4:}\label{cluster-4}

Cluster 4, with the top hashtag \#fitcheck, shows a high purity of
76.92\% and a low entropy of 0.99. This indicates that the majority of
posts in this cluster are centered around the theme of fashion and
self-expression, particularly through outfit sharing (\#fitcheck). The
content here is highly focused on personal style and self-image, and
likely intersects with recovery themes, showing a consistent focus on
fashion as a form of self-empowerment.

\subsubsection{Summary:}\label{summary}

\begin{itemize}
\item
  \textbf{Cluster 1} has a moderate focus on college life and related
  mental health experiences, though there is some diversity in the
  content.
\item
  \textbf{Cluster 2} is highly mixed and noisy, with no clear dominant
  theme, despite a focus on individual milestones or recognition.
\item
  \textbf{Cluster 3} is tightly focused on exercise addiction recovery,
  with a high degree of consistency within the posts.
\item
  \textbf{Cluster 4} is centered on fashion and self-expression, with a
  consistent theme of personal style and self-image in recovery.
\end{itemize}

\end{document}
